### ISSUE TITLE
Nexus 4 Android 5.0.1 Crash with a stock rom

### ISSUE THREAD

**Issue by JohnMcLear** [chariotsolutions/phonegap-nfc#159]
Just witnessed an app crash on NFC Write on this device

**Comment by JohnMcLear** [comment]
The crash Im getting is:

```
java.lang.IllegalStateException: Close other technology first!
at android.nfc.Tag.setConnectedTechnology(Tag.java:458)
at android.nfc.tech.BasicTagTechnology.connect(BasicTagTechnology.java:78)
at android.nfc.tech.Ndef.connect(Ndef.java:71)
at com.chariotsolutions.nfc.plugin.NfcPlugin$1.run(NfcPlugin.java:196)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

Does that help @don  ?

**Comment by don** [comment]
@JohnMcLear `nfc.share` is working with Cordova 4.2.0 on Nexus 4 with Android 5.0.1

Can you try and duplicate the problem with this test project https://github.com/don/nfc-share?

**Comment by don** [comment]
@JohnMcLear try this project https://github.com/don/phonegap-nfc-issue-150

It worked with Cordova 4.2.0 on Nexus 4 with Android 5.0.1 writing to a Mifare Ultralight C tag.

**Comment by don** [comment]
Can't duplicate. Re-open and include sample code if still a problem.
