### ISSUE TITLE
Error installing the plugin

### ISSUE THREAD

**Issue by fixdaddy** [chariotsolutions/phonegap-nfc#374]
Following the Getting Started instructions for CLI, got the following error installing the plugin.

C:\Users\NDS\nfc2>cordova plugin add phonegap-nfc
Installing "phonegap-nfc" for android
Failed to install 'phonegap-nfc': Error: Unable to graft xml at selector "/manif
est/uses-sdk" from "C:\Users\NDS\nfc2\platforms\android\app\src\main\AndroidMani
fest.xml" during config install
    at ConfigFile_graft_child [as graft_child] (C:\Users\NDS\nfc2\node_modules\c
ordova-common\src\ConfigChanges\ConfigFile.js:122:19)
    at PlatformMunger_apply_file_munge [as apply_file_munge] (C:\Users\NDS\nfc2\
node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:81:34)
    at munge_helper (C:\Users\NDS\nfc2\node_modules\cordova-common\src\ConfigCha
nges\ConfigChanges.js:252:14)
    at PlatformMunger.add_plugin_changes (C:\Users\NDS\nfc2\node_modules\cordova
-common\src\ConfigChanges\ConfigChanges.js:159:12)
    at C:\Users\NDS\nfc2\node_modules\cordova-common\src\PluginManager.js:123:29

    at _fulfilled (C:\Users\NDS\nfc2\node_modules\q\q.js:854:54)
    at C:\Users\NDS\nfc2\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\NDS\nfc2\node_modules\q\q.js:81
6:13)
    at C:\Users\NDS\nfc2\node_modules\q\q.js:877:14
    at runSingle (C:\Users\NDS\nfc2\node_modules\q\q.js:137:13)
Unable to graft xml at selector "/manifest/uses-sdk" from "C:\Users\NDS\nfc2\pla
tforms\android\app\src\main\AndroidManifest.xml" during config install

Unfortunately, the Phonegap Build also gave me an error...

Please help!

**Comment by fixdaddy** [comment]
It worked eventually.
